# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - studentperfcheck

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://studentperf.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_08dcaad3a602489fa900a3142856fb3c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_071a40800b1b40a79440005438ead72e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: studentperf.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_08dcaad3a602489fa900a3142856fb3c }}/perfcheck:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'studentperfcheck'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_00356e549b6b4fd5be10f6539a3ba23f }}
        images: 'studentperf.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_08dcaad3a602489fa900a3142856fb3c }}/perfcheck:${{ github.sha }}'